bases:
  - ../../base

namespace: prod-namespace

resources:
  - namespace.yaml

configMapGenerator:
  - name: app-config
    files:
      - configmap-prod.yaml

images:
  - name: berluseden/helloworld
    newName: berluseden/helloworld
    newTag: latest

patchesStrategicMerge:
  - configmap-prod.yaml
