bases:
  - ../../base

namespace: dev-api-namespace

resources:
  - namespace.yaml

configMapGenerator:
  - name: app-config
    files:
      - configmap-api-dev.yaml

images:
  - name: berluseden/helloworld-api
    newName: berluseden/helloworld-api
    newTag: latest
