apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-api
  labels:
    app: helloworld-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-api
  template:
    metadata:
      labels:
        app: helloworld-api
    spec:
      containers:
        - name: helloworld-api
          image: berluseden/helloworld-api:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
