apiVersion: v1
kind: Service
metadata:
  name: helloworld-api
  labels:
    app: helloworld-api
spec:
  selector:
    app: helloworld-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
