apiVersion: v1
kind: Service
metadata:
  name: helloword-api
  labels:
    app: helloword-api
spec:
  selector:
    app: helloword-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
